### PR TITLE
Update syllabus.html

### PR DESCRIPTION
**Pull request by callinSwitzer**
changed list of objectives to match R ecology lesson

### CODE REVIEW

**Comment by arokem** [comment]
Might be worth sending this upstream to https://github.com/carpentries/workshop-template?

**Comment by callinSwitzer** [comment]
Sure. I'll give it a try.

**Comment by callinSwitzer** [comment]
I looked at their lessons, and they're quite a bit different from what you're using at UW.  It looks like they're not using the R Ecology Lesson in the workshop template.   I will leave the upstream version as it is for now.

**Comment by arokem** [comment]
OK. Thanks for looking into it!

**Pull request merged**
